### ISSUE TITLE
Forcing to http version 1.0 causes issue in the newest version of Magento 2.4.7

### ISSUE THREAD

**Issue by maxwhite** [RadarsofthouseDev/billwerk-plus-subscription-for-magento2#1]
When testing on Magento 2.4.7 we get error: 

_HTTP/1 is not supported by the cURL handler._

What is the purpose of forcing to http 1.0 version ?

https://github.com/RadarsofthouseDev/billwerk-plus-optimize-for-magento2/blob/b3d6adb685afb186b8f8bfbfb752aafebd66b2be/Client/Api.php#L244

Envoronment to reproduce :

 - Magento ver. 2.4.7-p3
 - guzzlehttp/guzzle: 7.9.2
 - PHP Version 8.3.13
 
How to fix: 

removing this line sets the http verson to default 1.1 and it stars working

**Comment by CommandoDK** [comment]
Hello Maxwhite
Thank you for the report. A developer is on the case.

**Comment by RadarsofthouseDev** [comment]
@maxwhite  , We've resolved the issue in Version 1.0.10 :)
