### ISSUE TITLE
Empty array key exception 

### ISSUE THREAD

**Issue by maxwhite** [RadarsofthouseDev/billwerk-plus-subscription-for-magento2#2]
This value is not required we need to check if it is empy or not to prevent errors. 

https://github.com/RadarsofthouseDev/billwerk-plus-optimize-for-magento2/blob/b3d6adb685afb186b8f8bfbfb752aafebd66b2be/Block/Adminhtml/Catalog/Product/Edit/Tab/Subscription/Preview.php#L103

Other values from subscription plan response might also be optional. You can check the in the documentation

**Comment by CommandoDK** [comment]
Hello Maxwhite
Thank you for the report. A developer is investigating.

**Comment by RadarsofthouseDev** [comment]
@maxwhite , We've resolved the issue in Version 1.0.10 :)
